import React from "react"
import "bootstrap/dist/css/bootstrap.min.css"
import "./mysplit.css"
import { Container, Row, Col } from "react-bootstrap"

export default function Mysplit() {
    return (
        <div>
            <Row>
            <Col md={6} className="bg-dark left-nav">
                <p className="nav-header">asdyasd</p>
            </Col>
            <Col md={6} className="bg-primary">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo felis, venenatis quis tincidunt sit amet, tincidunt sed neque. Curabitur et dui nisi. Nunc tempor tempus mauris, ut feugiat magna consequat vitae. Phasellus et est at odio feugiat scelerisque sed id purus. Quisque fringilla dictum urna, ac egestas dolor ornare vel. Integer vitae ante convallis, convallis nulla sed, rutrum neque. Praesent id eros eget est euismod fermentum. Aenean et orci fermentum nulla feugiat eleifend. Fusce in orci volutpat, fringilla ipsum dignissim, facilisis velit. Vestibulum in elit quis lacus suscipit maximus id eu risus. Aenean pellentesque id orci a mollis. In nunc turpis, auctor consectetur tempus non, volutpat ut felis. Vestibulum luctus dolor id lacus accumsan scelerisque at a felis. Nullam nec ante non dolor ornare porttitor laoreet vitae metus. Nam vestibulum, urna nec laoreet condimentum, risus ligula sollicitudin justo, consequat luctus risus dui et eros.

Curabitur iaculis metus gravida, tincidunt ligula et, accumsan tortor. Fusce pretium ultricies felis, nec placerat risus commodo in. Nam sagittis magna at mi elementum luctus. Nunc viverra leo mauris, eget tincidunt justo pretium id. Vestibulum orci sem, hendrerit id velit in, lobortis tincidunt odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis consequat lacus, et rhoncus urna tristique eu. Nulla imperdiet tortor at arcu sagittis semper. Suspendisse congue elit vitae posuere ullamcorper. Aenean id eros lacinia, aliquam est vel, ullamcorper nisi. Integer facilisis diam massa, sit amet pulvinar nunc elementum id. Mauris sit amet felis odio. Maecenas metus nibh, elementum quis elit sit amet, consectetur ultricies velit. Suspendisse turpis massa, suscipit id libero vel, rhoncus ultricies neque. Mauris at blandit enim. Nullam eu lacinia nisi.

Praesent et nisi nec dolor bibendum tincidunt quis nec ante. Nullam ac dictum ligula. In fringilla enim non metus auctor, in tincidunt tellus sodales. Nunc in consequat sapien, et gravida magna. Donec vel ipsum vel ipsum malesuada pretium sit amet eu diam. Maecenas iaculis condimentum condimentum. Sed ac tortor a mi pulvinar hendrerit nec et turpis. Vestibulum luctus, mauris sit amet lacinia elementum, tellus felis dignissim risus, quis vehicula felis ligula lacinia ipsum. Proin faucibus facilisis facilisis. Suspendisse facilisis vestibulum tempor. Vivamus convallis, ligula et consequat ultricies, ipsum metus ultrices nisl, id consequat quam sem sed diam. Ut diam urna, condimentum vel enim eu, eleifend euismod nisi.

Vestibulum eget lobortis purus, non laoreet leo. Morbi egestas augue ut ex interdum, ac vulputate sem efficitur. In hac habitasse platea dictumst. Aliquam erat volutpat. Morbi mollis in ligula non accumsan. Morbi eget efficitur nisl, id scelerisque justo. Sed non ultrices leo, quis hendrerit massa. Aenean quis nulla diam. Phasellus ex dolor, pulvinar ac posuere sagittis, condimentum eu est. Phasellus mollis purus et vulputate volutpat. Maecenas ut ex ut mauris condimentum tempus. Vestibulum tortor risus, ornare in pulvinar eget, scelerisque ac velit. Vestibulum gravida consequat mauris, id congue nibh tempus ut. Morbi laoreet, odio id condimentum scelerisque, neque augue pellentesque risus, gravida rhoncus ex erat vel leo. Donec nec accumsan mi, eget commodo mauris. Vivamus erat nisl, mattis nec faucibus id, mollis eu dolor.

Nulla non scelerisque sapien, ut scelerisque nibh. Integer elit risus, pulvinar eleifend vestibulum eu, bibendum et ante. Sed libero diam, iaculis ac vehicula eget, pellentesque ut magna. Ut vitae ultricies nunc. Aenean venenatis, ligula a sollicitudin luctus, mi sem sollicitudin leo, vel porttitor nisi metus eget nibh. Vestibulum cursus ipsum id vulputate consectetur. Nunc in urna et odio hendrerit commodo. Pellentesque ac orci ut risus ultrices posuere. Maecenas eget dolor ac risus tincidunt maximus.

Duis vitae nisi justo. Nunc accumsan augue urna, id sagittis lorem mattis nec. Praesent gravida ipsum in nisl commodo facilisis. Aliquam erat volutpat. Curabitur laoreet tincidunt turpis nec ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc efficitur eleifend mauris, eu semper elit tristique sed.

Ut quis suscipit erat. Nulla nec neque est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc luctus magna nisl, scelerisque ornare sapien convallis eu. Aliquam dignissim suscipit neque sed lacinia. Suspendisse potenti. Sed nec dignissim nulla, ut posuere sem. Suspendisse a nibh ac ex gravida malesuada.

Nunc enim est, consectetur ut justo a, dapibus lacinia ligula. Integer tortor urna, scelerisque nec lectus eget, viverra dignissim enim. Duis vitae ultricies nisl. Quisque ut erat pretium tellus porta convallis vel et dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. In egestas, nisl vitae malesuada facilisis, purus massa congue mi, id tincidunt sem massa et ipsum. In vulputate rhoncus ipsum non laoreet. Nulla orci erat, vulputate non eros placerat, aliquam tempor sem. Maecenas a lectus dapibus, porta ex vitae, aliquet massa. Fusce fringilla turpis id hendrerit suscipit. Donec quis turpis non enim interdum auctor. Donec semper, nunc a imperdiet congue, tellus lorem mollis orci, at imperdiet erat est sollicitudin sapien.

Mauris mi sem, commodo sit amet tristique ultrices, semper nec mi. Proin dictum hendrerit vulputate. Ut dolor ex, scelerisque in lacinia in, suscipit non ipsum. Quisque facilisis posuere arcu, eu vehicula dolor cursus in. Vivamus rhoncus finibus sodales. Fusce rhoncus diam vitae iaculis cursus. Proin fermentum, turpis sed elementum hendrerit, odio ante varius elit, quis egestas metus erat at ligula. Nullam a ex tincidunt massa aliquam consectetur porta eget ligula. Pellentesque dignissim finibus mauris, ultricies porta turpis tempor sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vestibulum vehicula molestie.

Proin mauris sem, consectetur vitae sodales sit amet, elementum eget lacus. Suspendisse in ipsum elit. Nam nunc enim, ornare sed dictum dictum, placerat id libero. Nam luctus dignissim laoreet. Pellentesque sodales massa at enim consequat, vitae volutpat nibh bibendum. Aenean sed tempus velit. Fusce dignissim mauris a metus lobortis faucibus. Sed orci justo, iaculis id nulla ut, ullamcorper condimentum nibh. Vestibulum eget iaculis turpis. Donec bibendum sit amet lectus sed rhoncus. Curabitur fringilla ultrices blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi bibendum augue orci, ut efficitur nisl venenatis sit amet.</p>
            </Col>
            </Row>

            <Row>
            <Col md={6} className="bg-warning left-nav">
                <p className="nav-header">different heading</p>
            </Col>
            <Col md={6} className="bg-info">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce justo felis, venenatis quis tincidunt sit amet, tincidunt sed neque. Curabitur et dui nisi. Nunc tempor tempus mauris, ut feugiat magna consequat vitae. Phasellus et est at odio feugiat scelerisque sed id purus. Quisque fringilla dictum urna, ac egestas dolor ornare vel. Integer vitae ante convallis, convallis nulla sed, rutrum neque. Praesent id eros eget est euismod fermentum. Aenean et orci fermentum nulla feugiat eleifend. Fusce in orci volutpat, fringilla ipsum dignissim, facilisis velit. Vestibulum in elit quis lacus suscipit maximus id eu risus. Aenean pellentesque id orci a mollis. In nunc turpis, auctor consectetur tempus non, volutpat ut felis. Vestibulum luctus dolor id lacus accumsan scelerisque at a felis. Nullam nec ante non dolor ornare porttitor laoreet vitae metus. Nam vestibulum, urna nec laoreet condimentum, risus ligula sollicitudin justo, consequat luctus risus dui et eros.

Curabitur iaculis metus gravida, tincidunt ligula et, accumsan tortor. Fusce pretium ultricies felis, nec placerat risus commodo in. Nam sagittis magna at mi elementum luctus. Nunc viverra leo mauris, eget tincidunt justo pretium id. Vestibulum orci sem, hendrerit id velit in, lobortis tincidunt odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis consequat lacus, et rhoncus urna tristique eu. Nulla imperdiet tortor at arcu sagittis semper. Suspendisse congue elit vitae posuere ullamcorper. Aenean id eros lacinia, aliquam est vel, ullamcorper nisi. Integer facilisis diam massa, sit amet pulvinar nunc elementum id. Mauris sit amet felis odio. Maecenas metus nibh, elementum quis elit sit amet, consectetur ultricies velit. Suspendisse turpis massa, suscipit id libero vel, rhoncus ultricies neque. Mauris at blandit enim. Nullam eu lacinia nisi.

Praesent et nisi nec dolor bibendum tincidunt quis nec ante. Nullam ac dictum ligula. In fringilla enim non metus auctor, in tincidunt tellus sodales. Nunc in consequat sapien, et gravida magna. Donec vel ipsum vel ipsum malesuada pretium sit amet eu diam. Maecenas iaculis condimentum condimentum. Sed ac tortor a mi pulvinar hendrerit nec et turpis. Vestibulum luctus, mauris sit amet lacinia elementum, tellus felis dignissim risus, quis vehicula felis ligula lacinia ipsum. Proin faucibus facilisis facilisis. Suspendisse facilisis vestibulum tempor. Vivamus convallis, ligula et consequat ultricies, ipsum metus ultrices nisl, id consequat quam sem sed diam. Ut diam urna, condimentum vel enim eu, eleifend euismod nisi.

Vestibulum eget lobortis purus, non laoreet leo. Morbi egestas augue ut ex interdum, ac vulputate sem efficitur. In hac habitasse platea dictumst. Aliquam erat volutpat. Morbi mollis in ligula non accumsan. Morbi eget efficitur nisl, id scelerisque justo. Sed non ultrices leo, quis hendrerit massa. Aenean quis nulla diam. Phasellus ex dolor, pulvinar ac posuere sagittis, condimentum eu est. Phasellus mollis purus et vulputate volutpat. Maecenas ut ex ut mauris condimentum tempus. Vestibulum tortor risus, ornare in pulvinar eget, scelerisque ac velit. Vestibulum gravida consequat mauris, id congue nibh tempus ut. Morbi laoreet, odio id condimentum scelerisque, neque augue pellentesque risus, gravida rhoncus ex erat vel leo. Donec nec accumsan mi, eget commodo mauris. Vivamus erat nisl, mattis nec faucibus id, mollis eu dolor.

Nulla non scelerisque sapien, ut scelerisque nibh. Integer elit risus, pulvinar eleifend vestibulum eu, bibendum et ante. Sed libero diam, iaculis ac vehicula eget, pellentesque ut magna. Ut vitae ultricies nunc. Aenean venenatis, ligula a sollicitudin luctus, mi sem sollicitudin leo, vel porttitor nisi metus eget nibh. Vestibulum cursus ipsum id vulputate consectetur. Nunc in urna et odio hendrerit commodo. Pellentesque ac orci ut risus ultrices posuere. Maecenas eget dolor ac risus tincidunt maximus.

Duis vitae nisi justo. Nunc accumsan augue urna, id sagittis lorem mattis nec. Praesent gravida ipsum in nisl commodo facilisis. Aliquam erat volutpat. Curabitur laoreet tincidunt turpis nec ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc efficitur eleifend mauris, eu semper elit tristique sed.

Ut quis suscipit erat. Nulla nec neque est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc luctus magna nisl, scelerisque ornare sapien convallis eu. Aliquam dignissim suscipit neque sed lacinia. Suspendisse potenti. Sed nec dignissim nulla, ut posuere sem. Suspendisse a nibh ac ex gravida malesuada.

Nunc enim est, consectetur ut justo a, dapibus lacinia ligula. Integer tortor urna, scelerisque nec lectus eget, viverra dignissim enim. Duis vitae ultricies nisl. Quisque ut erat pretium tellus porta convallis vel et dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. In egestas, nisl vitae malesuada facilisis, purus massa congue mi, id tincidunt sem massa et ipsum. In vulputate rhoncus ipsum non laoreet. Nulla orci erat, vulputate non eros placerat, aliquam tempor sem. Maecenas a lectus dapibus, porta ex vitae, aliquet massa. Fusce fringilla turpis id hendrerit suscipit. Donec quis turpis non enim interdum auctor. Donec semper, nunc a imperdiet congue, tellus lorem mollis orci, at imperdiet erat est sollicitudin sapien.

Mauris mi sem, commodo sit amet tristique ultrices, semper nec mi. Proin dictum hendrerit vulputate. Ut dolor ex, scelerisque in lacinia in, suscipit non ipsum. Quisque facilisis posuere arcu, eu vehicula dolor cursus in. Vivamus rhoncus finibus sodales. Fusce rhoncus diam vitae iaculis cursus. Proin fermentum, turpis sed elementum hendrerit, odio ante varius elit, quis egestas metus erat at ligula. Nullam a ex tincidunt massa aliquam consectetur porta eget ligula. Pellentesque dignissim finibus mauris, ultricies porta turpis tempor sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vestibulum vehicula molestie.

Proin mauris sem, consectetur vitae sodales sit amet, elementum eget lacus. Suspendisse in ipsum elit. Nam nunc enim, ornare sed dictum dictum, placerat id libero. Nam luctus dignissim laoreet. Pellentesque sodales massa at enim consequat, vitae volutpat nibh bibendum. Aenean sed tempus velit. Fusce dignissim mauris a metus lobortis faucibus. Sed orci justo, iaculis id nulla ut, ullamcorper condimentum nibh. Vestibulum eget iaculis turpis. Donec bibendum sit amet lectus sed rhoncus. Curabitur fringilla ultrices blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi bibendum augue orci, ut efficitur nisl venenatis sit amet.</p>
            </Col>
            </Row>
        </div>
    )
}
